kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: kubeflow-trainer
nodes:
  - role: control-plane
  - role: worker
    labels:
      node-role: trainer-worker
  - role: worker
    labels:
      node-role: trainer-worker
